// This file is auto-generated by @hey-api/openapi-ts

export type WeatherForecast = {
    date?: Date;
    temperatureC?: number;
    readonly temperatureF?: number;
    summary?: string | null;
};

export type GetWeatherForecastResponse = Array<WeatherForecast>;

export type GetWeatherForecastError = unknown;

export type GetWeatherForecastResponseTransformer = (
    data: any,
) => Promise<GetWeatherForecastResponse>;

export type WeatherForecastModelResponseTransformer = (data: any) => WeatherForecast;

export const WeatherForecastModelResponseTransformer: WeatherForecastModelResponseTransformer = (
    data,
) => {
    if (data?.date) {
        data.date = new Date(data.date);
    }
    return data;
};

export const GetWeatherForecastResponseTransformer: GetWeatherForecastResponseTransformer = async (
    data,
) => {
    if (Array.isArray(data)) {
        data.forEach(WeatherForecastModelResponseTransformer);
    }
    return data;
};
